# Generated by Django 4.0 on 2023-10-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchboard', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
