# Generated by Django 4.0 on 2023-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchboard', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
