# Generated by Django 4.0 on 2023-10-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchboard', '0008_user_other_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other_user',
        ),
    ]
