# Generated by Django 4.0 on 2023-10-30 17:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sketchboard', '0009_remove_user_other_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=100000)),
                ('currentuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sketchboard.user')),
            ],
        ),
    ]
